services:
  postgres:
    container_name: ${POSTGRES_CONTAINER_NAME}
    image: postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /data/postgres # Pasta dentro do container para armazenar os dados do banco de dados
    volumes:
      - ./data/pg:/data/postgres # Pasta local para persistir os dados do banco de dados
    env_file:
      - .env
